src/server/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class AddUserForm(FlaskForm):
    """
    A Form to add new users
    """
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    is_admin = BooleanField('Admin')
    submit = SubmitField('Add user')


class ChangePasswordForm(FlaskForm):
    """
    A Form to change the password of the current user
    """
    current_password = PasswordField("Current Password", validators=[DataRequired])
    new_password = PasswordField("New Password", validators=[DataRequired])
    confirmed_new_password = PasswordField("Confirm New Password", validators=[DataRequired])
    submit = SubmitField('Change password')

src/server/admin/routes.py
from argon2 import PasswordHasher, Type
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

from server import db
from server.admin.admin_functions import display_all_spotify_users, display_spotify_user_playlists, display_user, \
    display_all_users, password_complex_enough
from server.admin.forms import ChangePasswordForm
from server.main.modals import User

mod = Blueprint("admin", __name__, template_folder='templates')


@mod.route("/spotify-users")
@login_required
def spotify_users() -> render_template:
    """
    Display one or all spotify users depending on the args in the url
    :return:
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the spotify id of a use in a url
    spotify_user_id = request.args.get("spotify-user-id")

    # Check if a use id is present in the url
    if spotify_user_id:
        return display_spotify_user_playlists(spotify_user_id)
    else:
        return display_all_spotify_users()


@mod.route("/users")
@login_required
def users() -> render_template:
    """
    Display the users or one user
    :return: A rendered template
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the user-id from the url
    user_id = request.args.get("user-id")

    # Check if a user id is given in the url
    if user_id:
        return display_user(user_id)

    return display_all_users()


@mod.route("/user/change_password", methods=["POST", "GET"])
def edit_user() -> redirect:
    """
    Edit the user password
    :return: a redirect to the user page
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the user-id from the url
    user_id = request.args.get("user-id")

    # Check if a user id is given in the url
    if not user_id:
        flash({"contend": "No user id was provided", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    if current_user.id != int(user_id) and not current_user.is_root:
        return render_template("authorisation_error.html", title="403")

    form = ChangePasswordForm()

    if form.confirmed_new_password.data == (None or "") and form.new_password.data == (None or "") \
            and form.current_password.data == (None or ""):
        flash({"contend": "You did not input all the required forms", "type": "bg-warning"})
        return redirect(url_for("admin.users") + f"?user-if={user_id}")

    # checks if all relevant data filed have been filled
    if current_user.check_password(form.current_password.data) or \
            (current_user.is_root and not current_user.id == int(user_id)):

        if form.new_password.data == form.confirmed_new_password.data:

            if not password_complex_enough(form.new_password.data):
                flash({"contend": "The password is not complex enough. (Upper + Lower + Digits)", "type": "bg-warning"})

            user = User.query.filter(User.id == int(user_id)).first()
            user.set_password(form.confirmed_new_password.data)
            db.session.commit()
            return redirect(url_for("admin.users") + f"?user-id={user.id}")
        else:
            flash({"contend": "The passwords did not match", "type": "bg-warning"})
            return redirect(url_for("admin.users") + f"?user-id={user_id}")

    else:
        flash({"contend": "You provided the wrong password", "type": "bg-warning"})
        return redirect(url_for("admin.users") + f"?user-id={user_id}")


@mod.route("/user/add", methods=["POST", "GET"])
@login_required
def add_user() -> redirect:
    """
    Add a new user
    :return: a redirect to the user page
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    password = request.form["password"]
    username = request.form["username"]

    # Check if the user should be a admin
    if "is_admin" in request.form:
        admin = True
    else:
        admin = False

    if password is None or username is None or username == "":
        flash({"contend": "You did not fill a username or password", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    # Check if the username already exists and do nothing if the user exists
    if User.query.filter(User.username == username).first():
        flash({"contend": "The user already exists", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    # Create a password hasher
    ph = PasswordHasher(type=Type.ID)

    if not password_complex_enough(password):
        flash({"contend": "The password is not complex enough. (Upper + Lower + Digits)", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    password_hash = ph.hash(password)

    # Create the neu user and add it into the database
    user = User(username=username, password_hash=password_hash, is_admin=admin)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("admin.users"))

src/server/admin/templates/spotify_user/spotify_user_playlists.html
{% extends "base.html" %}

{% block javascript_variables %}
    <script type="text/javascript">
        let removePlaylistAPI = "{{ url_for("api.remove_playlist") }}?playlist-id=";
        let addPlaylistAPI = "{{ url_for("api.add_playlist") }}?playlist-id=";
        let playlistDurationAPI = "{{ url_for("api.update_playlist_duration")}}?playlist-id=";
        let playbackControlAPI = "{{ url_for("api.toggle_playback_control", spotify_user_id=spotify_user_id)}}?queue=";
        let autocomplete = {
            {%   for key, value in autocomplete_playlist_list.items() %}
                "{{ key }}": "{{ value }}",
            {% endfor %}
        };
    </script>
{% endblock %}

{% block main %}

    <div class="center">
        <h3>{{ user_name }}</h3>
    </div>

    <h5>Playlists</h5>
    <div class="table-wrapper">
        <table class="striped highlight own-responsive-table small-margin-bottom">
            <thead>
            <tr>
                <th data-sort-default>Name</th>
                <th>Author</th>
                <th data-sort-method='number'>Track count</th>
                <th class="song-length" data-sort-method='none'>Max. song length</th>
                <th style="width: 1px" data-sort-method='none'></th>
            </tr>
            </thead>
            <tbody id="insert">

            {# Check if spotify user has a playlist #}
            {% if playlist_list_json != {} %}

                {# For every playlist the spotify user has #}
                {% for playlist_id, playlist in playlist_list_json.items() %}
                    <tr class="playlist">
                        <td>
                            <a class="black-text pointer underline" hover-on-touch
                               onclick="window.open('{{ playlist.url }}')"> {{ playlist["name"] }}</a>
                        </td>
                        <td>
                            <a class="black-text pointer underline" hover-on-touch
                               onclick="window.open('{{ playlist.author.url }}')">{{ playlist.author.name }}</a>
                        </td>
                        <td>{{ playlist.track_count }}</td>
                        <td class="song-length no-padding">
                            <input onkeydown="onlyNumbers()" class="no-margin" type="number"
                                   id="{{ playlist_id }}-input" autocomplete="off"
                                   default-duration="{{ playlist.max_song_duration }}"
                                   value="{{ playlist.max_song_duration }}">
                        </td>
                        <td>
                            <i tabindex="0" class="material-icons pointer primary-text-color" id="{{ playlist_id }}">delete</i>
                        </td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr id="no-playlists-placeholder">
                    <td></td>
                    <td></td>
                    <td class="center-align">No Playlists</td>
                    <td></td>
                    <td></td>
                </tr>
            {% endif %}

            </tbody>
        </table>
    </div>

    <div class="row flex-v-center">
        <div class="input-field col s5 no-padding-left">
            <input id="playlist-id" class="autocomplete" type="text">
            <label for="playlist-id" style="left: 0;">Playlist ID</label>
        </div>
        <div class="input-field col s5">
            <input id="songlength-id" type="number" value="0" autocomplete="off" onkeydown="onlyNumbers(event)">
            <label for="songlength-id">Song Length in sec</label>
        </div>
        <button class="btn-flat col s2 primary-bg-color white-text" id="add-button">Add</button>
    </div>


    <h5>Playback Control</h5>
    <div class="switch margin-bottom">
        <label>
            Off
            <input type="checkbox" id="playback-control" autocomplete="off" {{ queue }}>
            <span class="lever"></span>
            Allow the playback being controlled by other users
        </label>
    </div>

{% endblock %}



{% block javascript %}
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/add.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/remove.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/queue.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/edit.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/main.js"></script>
{% endblock %}

src/server/admin/templates/spotify_user/spotify_users.html
{% extends "base.html" %}

{% block javascript_variables %}
    <script>
        let deleteSpotifyUserAPI = "{{ url_for("api.remove_spotify_user") }}?spotify-user-id=";
    </script>
{% endblock %}

{% block main %}

    <div class="center">

        <h3>Spotify Users</h3>

        <div class="table-wrapper">
            <table class="striped highlight own-responsive-table">
                <thead>
                <tr>
                    <th data-sort-default>Username</th>
                    <th>Country</th>
                    <th data-sort-method='number'>Playlists</th>
                    <th data-sort-method='number'>Followers</th>
                    <th style="width: 1px" data-sort-method='none'></th>
                    <th style="width: 1px" data-sort-method='none'></th>
                </tr>
                </thead>
                <tbody>

                {# Check if there are spotify users#}
                {% if spotify_users != {} %}

                    {# For every user create a row #}
                    {% for user_id, user in spotify_users.items() %}

                        <tr class="spotify-user">
                            <td>
                                <a class="black-text pointer underline" hover-on-touch
                                   href="{{ user.external_urls.spotify }}" target="_blank">{{ user.display_name }}</a>
                            </td>
                            <td>{{ user.country }}</td>
                            <td>{{ user.playlist_count }}</td>
                            <td>{{ user.followers.total }}</td>
                            <td><a class="material-icons pointer black-text"
                                   href="{{ url_for("admin.spotify_users") }}?spotify-user-id={{ user.id }}">edit</a>
                            </td>
                            <td>
                                <i tabindex="0" class="material-icons pointer primary-text-color" id="{{ user_id }}">delete</i>
                            </td>
                        </tr>

                    {% endfor %}

                    {# Show that no playlists are availabel #}
                {% else %}

                    <tr id="user-placeholder">

                        <td></td>
                        <td></td>
                        <td>No Users</td>
                        <td></td>
                        <td></td>
                        <td></td>

                    </tr>

                {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    {# Show floating button that redirects the user to spotify #}
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large" href="{{ url_for("api.authorize") }}">
            <i class="very-large large material-icons">add</i>
        </a>
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="/static/js/own/spotify_users/main.js"></script>
{% endblock %}

src/server/admin/templates/spotify_user_playlists.html
{% extends "base.html" %}

{% block javascript_variables %}
    <script type="text/javascript">
        let removePlaylistAPI = "{{ url_for("api.remove_playlist") }}?playlist-id=";
        let addPlaylistAPI = "{{ url_for("api.add_playlist") }}?playlist-id=";
        let playlistAPI = "{{ url_for("api.get_playlist") }}?playlist-id=";
        let autocomplete = {
            {%   for key, value in updated_playlist_list.items() %}
                "{{ key }}": "{{ value }}",
            {% endfor %}
        };
    </script>
{% endblock %}

{% block main %}

    <div class="center">
        <h3>{{ user_name }}'s Playlists</h3>
    </div>

    <div class="table-wrapper">
        <table class="striped highlight own-responsive-table">
            <thead>
            <tr>
                <th data-sort-default>Name</th>
                <th>Author</th>
                <th data-sort-method='number'>Track count</th>
                <th style="width: 1px" data-sort-method='none'></th>
            </tr>
            </thead>
            <tbody id="insert">

            {# Check if spotify user has a playlist #}
            {% if playlist_list_json != {} %}

                {# For every playlist the spotify user has #}
                {% for playlist_id, playlist in playlist_list_json.items() %}
                    <tr class="playlist">
                        <td>
                            <a class="black-text pointer underline" hover-on-touch
                               onclick="window.open('{{ playlist.url }}')"> {{ playlist["name"] }}</a>
                        </td>
                        <td>
                            <a class="black-text pointer underline" hover-on-touch
                               onclick="window.open('{{ playlist.author.url }}')">{{ playlist.author.name }}</a>
                        </td>
                        <td>{{ playlist.track_count }}</td>
                        <td><i tabindex="0" class="material-icons pointer primary-text-color" id="{{ playlist_id }}">delete</i>
                        </td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr id="no-playlists-placeholder">
                    <td></td>
                    <td class="center-align">No Playlists</td>

                    <td></td>
                    <td></td>
                </tr>
            {% endif %}

            </tbody>
        </table>
    </div>
    <div class="left-align">
        <h4>Add Playlists</h4>
    </div>

    <div class="row flex-v-center">
        <div class="input-field col s10">
            <input id="playlist-id" class="autocomplete" type="text">
            <label for="playlist-id">Playlist ID</label>
        </div>
        <button class="btn-flat col s2 primary-bg-color white-text" id="add-button">Add</button>
    </div>

{% endblock %}



{% block javascript %}
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/add.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/remove.js"></script>
    <script type="text/javascript" src="/static/js/own/spotify_user_playlists/main.js"></script>
{% endblock %}

src/server/admin/templates/user/edit_user.html
{% extends "base.html" %}


{% block javascript_variables %}
    <script>
        let addUserToPlaylistAPI = "{{ url_for("api.add_playlists_to_user") }}";
        let removePlaylistFromUserAPI = "{{ url_for("api.remove_playlist_from_user") }}"
    </script>
{% endblock %}


{% block main %}

    {# User name #}
    <div class="center">
        <h3>{{ user.username }}</h3>
    </div>

    {# The table with the user playlists #}
    <div class="table-wrapper">
        <table class="striped highlight own-responsive-table">
            <thead>
            <tr>
                <th data-sort-default>Name</th>
                <th>ID</th>
                <th data-sort-method='number'>Tracks</th>
                <th>Author</th>
                <th style="width: 1px" data-sort-method='none'></th>
            </tr>
            </thead>

            {# Check if the user has a playlist #}
            {% if playlist_list != [] %}

                <tbody>

                {# Add a new row for every playlist#}
                {% for playlist in playlist_list %}
                    <tr class="playlist" id="{{ playlist.id }}">
                        <td>
                            <a class="pointer underline black-text playlist-name" hover-on-touch
                               onclick="window.open('{{ playlist.external_urls.spotify }}')">{{ playlist.name }}</a>
                        </td>
                        <td>{{ playlist.id }}</td>
                        <td>{{ playlist.tracks.total }}</td>
                        <td>
                            <a class="pointer underline black-text" hover-on-touch
                               onclick="window.open('{{ playlist.owner.external_urls.spotify }}')">{{ playlist.owner.display_name }}</a>
                        </td>
                        <td><i tabindex="0" class="material-icons pointer primary-text-color">delete</i></td>
                    </tr>
                {% endfor %}

                </tbody>

            {% else %}
                <tr id="no-playlists-placeholder">
                    <td></td>
                    <td></td>

                    <td class="center-align">No Playlists</td>

                    <td></td>
                    <td></td>
                </tr>
            {% endif %}


        </table>
    </div>

    {# Add playlist to user section #}
    <ul>
        <li class="divider"></li>
    </ul>

    <h5 class="margin-bottom">Add Playlists to User</h5>

    <div class="input-field col s12">
        <select aria-label="playlist-select" multiple id="playlist-select">

            {# Check if we can add playlists to the user #}
            {% if all_playlists_list != [] %}
                <option value="" disabled selected>Select a Playlist</option>

                {# Show all available playlists#}
                {% for playlist in all_playlists_list %}
                    <option value="{{ playlist.id }}">{{ playlist.name }}</option>
                {% endfor %}

            {% else %}
                <option value="" disabled selected>No Playlists available</option>
            {% endif %}

        </select>
    </div>

    {# The add button for the playlists #}
    <div class="right-align">
        <button class="waves-effect btn-flat" id="add-playlist">Add</button>
    </div>


    {% if current_user_id == user_id or current_user.is_root %}

        {# Modal to change the users password#}
        <div id="edit-password" class="modal">
            <form action="{{ url_for("admin.edit_user") }}?user-id={{ user.id }}" method="post">

                {# CSRF Token #}
                {{ form.csrf_token }}

                {# The contend of the modal #}
                <div class="modal-content">
                    <h4>Change user password</h4>
                    <div class="row flex-v-center">

                        {% if not current_user.is_root or (user_id == current_user.id and current_user.is_admin) %}
                            {# Current password #}
                            <div class="input-field col s12">
                                {{ form.current_password(size=32) }}
                                {{ form.current_password.label }}
                            </div>
                        {% endif %}

                    </div>

                    {# Checkbox admin #}
                    <div class="row">

                        {# New password #}
                        <div class="input-field col s6">
                            {{ form.new_password() }}
                            {{ form.new_password.label }}
                        </div>

                        <div class="input-field col s6">
                            {{ form.confirmed_new_password() }}
                            {{ form.confirmed_new_password.label }}
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    {# Cancel button #}
                    <button class="modal-close waves-effect btn-flat left">Cancel</button>

                    {# Submit button #}
                    {{ form.submit(class='btn-flat modal-close tabable', id="add-playlists") }}
                </div>
            </form>
        </div>


        {# The change password button #}
        <div class="fixed-action-btn">
            <a tabindex="0" class="btn-floating btn-large  modal-trigger" href="#edit-password">
                <i class="large material-icons">vpn_key</i>
            </a>
        </div>

    {% endif %}

{% endblock %}


{% block javascript %}
    <script type="text/javascript" src="/static/js/own/edit_user/add.js"></script>
    <script type="text/javascript" src="/static/js/own/edit_user/remove.js"></script>
    <script type="text/javascript" src="/static/js/own/edit_user/main.js"></script>
{% endblock %}

src/server/admin/templates/user/users.html
{% extends "base.html" %}

{% block javascript_variables %}
    <script>
        let deleteUserAPI = "{{ url_for("api.remove_user") }}?user-id="
    </script>
{% endblock %}

{% block main %}

    <div class="center">
        <h3>User Accounts</h3>
    </div>

    <div class="table-wrapper">
        <table class="striped highlight own-responsive-table">
            <thead>
            <tr>
                <th data-sort-default>Username</th>
                <th>Admin</th>
                <th data-sort-method='number'>Playlists</th>
                <th style="width: 1px" data-sort-method='none'></th>
                <th style="width: 1px" data-sort-method='none'></th>
            </tr>
            </thead>
            <tbody>

            {# Show every user #}
            {% for user in user_list %}

                <tr class="user">
                    <td>{{ user.username }}</td>
                    <td>{{ user.is_admin }}</td>
                    <td>{{ user.playlist_count }}</td>

                    <td>
                        <a class="material-icons pointer black-text"
                           href="{{ url_for("admin.users") }}?user-id={{ user.id }}">edit</a>
                    </td>
                    <td>
                        <a tabindex="0" class="material-icons pointer primary-text-color" id="{{ user.id }}">delete</a>
                    </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>


    {# Modal that allows the user to add new users #}
    <div id="add-modal" class="modal">
        <form action="{{ url_for("admin.add_user") }}" method="post">

            {# CSRF Token #}
            {{ form.csrf_token }}

            {# The contend of the modal #}
            <div class="modal-content">
                <h4>Add new User</h4>
                <div class="row flex-v-center">

                    {# Username #}
                    <div class="input-field col s6">
                        {{ form.username(size=32) }}
                        {{ form.username.label }}
                    </div>

                    <div class="input-field col s6">
                        {{ form.password }}
                        {{ form.password.label }}
                    </div>
                </div>

                {# Checkbox admin #}
                <div class="row">
                    <div class="col s12">
                        <div style="float: right;">
                            {{ form.is_admin(tabindex=-1) }}
                            {{ form.is_admin.label(tabindex=1) }}
                        </div>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                {# Cancel button #}
                <button class="modal-close waves-effect btn-flat left">Cancel</button>

                {# Submit button #}
                {{ form.submit(class='btn-flat modal-close tabable', id="add-playlists") }}
            </div>
        </form>
    </div>

    {# The add button #}
    <div class="fixed-action-btn">
        <a tabindex="0" class="btn-floating btn-large  modal-trigger" href="#add-modal">
            <i class="very-large large material-icons">add</i>
        </a>
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="/static/js/own/users/main.js"></script>
{% endblock %}