src/server/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """
    The login form
    """
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

src/server/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user, logout_user, login_user

from server import spotify
from server.api.api_functions import get_token_by_playlist, modify_playlist_json
from server.main.forms import LoginForm
from server.main.modals import User, Playlist, SpotifyUser

mod = Blueprint("main", __name__, template_folder='templates')


@mod.route("/")
@login_required
def home() -> render_template:
    """
    The default rote that lets you select a playlist
    :return: A template
    """

    user = current_user.id
    playlist_list = Playlist.query.join(User.playlists).filter(User.id == user).all()

    playlist_list_json = {}
    for playlist in playlist_list:
        auth_token = get_token_by_playlist(playlist.spotify_id)

        if auth_token:
            playlist_list_json[playlist.spotify_id] = \
                modify_playlist_json(spotify.playlist(playlist.spotify_id, auth_token))

    return render_template("select.html", title="Select Playlist", playlist_list_json=playlist_list_json)


@mod.route("/playlist/<playlist_id>")
@login_required
def playlist(playlist_id) -> render_template:
    # Get a playlist from the database
    spotify_playlist: Playlist = Playlist.query.filter(Playlist.spotify_id == playlist_id).first()

    # If the playlist is not in the db render the resource not found
    if not spotify_playlist:
        return render_template("resource_not_found.html", title="Resource not found", resource="Playlist")

    # Render the playlist page
    return render_template("playlist.html", title="Home", playlist_id=playlist_id, spotify_playlist=spotify_playlist)


@mod.route("/playback/<spotify_user_id>")
@login_required
def playback(spotify_user_id):
    spotify_user = SpotifyUser.query.filter(SpotifyUser.spotify_user_id == spotify_user_id).first()
    if not spotify_user:
        return render_template("resource_not_found.html", title="Resource not found", resource="Spotify User")

    # ToDo make secure
    # return render_template("angular/index.html", title="Playback", spotify_user_id="spotify_user_id")
    return render_template("playback.html", title="Playback", spotify_user_id=spotify_user_id)


@mod.route("/login", methods=["GET", "POST"])
def login() -> redirect:
    """
    Login page
    :return: A redirect
    """

    # Redirect the user to home if he is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()

    # checks if all relevant data filed have been filled
    if form.validate_on_submit():
        # get the user that logged in
        user = User.query.filter_by(username=form.username.data).first()

        # if the user does not exist or has the wrong password
        if user is None or not user.check_password(form.password.data):
            flash({"contend": "Invalid username or password", "type": "bg-warning"})
            return redirect(url_for("main.login"))

        # login the user
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if next_page:
            if not str(next_page[0]) == "/":
                next_page = "/" + next_page

            return redirect(f"{next_page}")
        else:
            return redirect(url_for("main.home"))

    # Handle invalid form
    if request.method == "POST":
        flash({"contend": "You missed some input fields", "type": "bg-warning"})
        return render_template('login.html', title='Sign In', form=form)

    return render_template('login.html', title='Sign In', form=form)


@mod.route("/logout")
@login_required
def logout():
    """
    Logout the user
    :return:
    """
    logout_user()
    return redirect(url_for('main.login'))

src/server/main/templates/angular/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Playback</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.09e2c710755c8867a460.css"></head>
<body>
  <app-root></app-root>
<script src="runtime-es2015.edb2fcf2778e7bf1d426.js" type="module"></script><script src="runtime-es5.edb2fcf2778e7bf1d426.js" nomodule defer></script><script src="polyfills-es5.6696c533341b95a3d617.js" nomodule defer></script><script src="polyfills-es2015.2987770fde9daa1d8a2e.js" type="module"></script><script src="main-es2015.3cdd5760efc058147066.js" type="module"></script><script src="main-es5.3cdd5760efc058147066.js" nomodule defer></script></body>
</html>

src/server/main/templates/index.html
{% extends "base.html" %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="../static/css/own/loading.css"
          media="screen,projection"/>

    <style>
        body {
            overflow-y: scroll !important;
        }
    </style>

{% endblock %}

{% block javascript_variables %}
    <script type="text/javascript">
        let searchAPI = "/api/spotify/search?playlist-id={{ playlist_id }}&searchterm=";
        let playlistAPI = "/api/spotify/playlist?playlist-id={{ playlist_id }}";
        let playlistTracksAPI = "/api/spotify/playlist/tracks?playlist-id={{ playlist_id }}";
        let playlistAddTracksAPI = "/api/spotify/playlist/add?playlist-id={{ playlist_id }}";
    </script>
{% endblock %}

{% block main %}

    <div id="main-box">
        <div class="container margin-top z-depth-3 rounded" id="playlist-box">

            <div class="center small-padding-top">
                <h1 id="playlist-name" style="display: none"></h1>
                <div class="loading-card small-padding-top small-padding-bottom small-margin-bottom"
                     style="border: none; margin: 2.8rem 0 1.68rem 0;" id="loading-heading">
                    <div class="loading-bar big-loading-bar loading first-loading-bar margin-auto"></div>
                </div>
            </div>

            <!-- Playlist information -->
            <div class="row flex-v-center">
                <div class="col s9">
                    <table style="display: none" id="playlist-description">
                        <tbody>
                        <tr>
                            <td>Author</td>
                            <td><a class="pointer underline black-text" id="author">HuiiBuh</a></td>
                        </tr>
                        <tr>
                            <td>Duration</td>
                            <td id="duration">22h</td>
                        </tr>
                        <tr>
                            <td>Song Count</td>
                            <td id="song-count">500</td>
                        </tr>
                        <tr style="border-bottom:none!important;">
                            <td>URL</td>
                            <td><a class="pointer underline black-text" id="playlist-url">Go to Spotify</a></td>
                        </tr>
                        </tbody>
                    </table>

                    <div class="loading-card" id="loading-playlist-description" style="overflow: hidden">
                        <div class="loading-bar loading-bar-2 loading first-loading-bar"></div>
                        {% for i in range(1, 3) %}
                            <div class="loading-bar loading-bar-3 loading "></div>
                            <div class="loading-bar loading-bar-1 loading "></div>
                            <div class="loading-bar loading-bar-2 loading "></div>
                            <div class="loading-bar loading-bar-1 loading "></div>
                        {% endfor %}
                    </div>

                </div>
                <div class="col s3 center no-padding">
                    <div class="loading-card rectangle">
                        <div class="image loading" id="playlist-cover"></div>
                    </div>
                </div>
            </div>
            <ul>
                <li class="divider"></li>
            </ul>
            <!-- Song heading -->
            <div class="row">
                <h4 class="col s12 no-margin-bottom">Songs</h4>
            </div>

            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="search-playlist-song" class="postfix-input" type="text">
                            <i class="material-icons postfix" id="clear-search-input">clear</i>
                            <label for="search-playlist-song">Search</label>
                            <span class="helper-text postfix-input" data-error="wrong" data-success="right">Search for songs in the playlist</span>
                        </div>
                    </div>
                </form>
            </div>

            <div id="search-results-block" style="display: none">
                <h5>Search Results</h5>
                <div id="search-results"></div>
            </div>

            <!-- All songs -->
            <div id="playlist-songs" style="display: none"></div>

            <div class="loading-card" id="song-placeholder">
                <div class="contend-loader">
                    <div class="loading-bar loading-bar-2 loading first-loading-bar"></div>

                    {% for i in range(1, 20) %}
                        <div class="loading-bar loading-bar-1 loading"></div>
                        <div class="loading-bar loading-bar-3 loading"></div>
                        <div class="loading-bar loading-bar-2 loading"></div>
                        <div class="loading-bar loading-bar-1 loading"></div>
                    {% endfor %}

                    <div class="loading-bar loading-bar-1 loading last-loading-bar"></div>
                </div>
            </div>

        </div>
    </div>


    <!-- Action button -->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large modal-trigger" href="#song-modal">
            <i class="very-large material-icons pointer">add</i>
        </a>
    </div>


    <div id="song-modal" class="modal">
        <div class="modal-content">
            <h4>Search for Songs</h4>

            <div class="row">
                <div class="col s12">
                    <div class="chip">artist:Eminem<i class="close material-icons">close</i></div>
                    <div class="chip">track:Lose Yourself<i class="close material-icons">close</i></div>
                    <div class="chip">album:8 Mile<i class="close material-icons">close</i></div>
                    <div class="chip">year:2002<i class="close material-icons">close</i></div>
                </div>
                <div class="input-field col s12" id="click-exception">
                    <i class="material-icons prefix" id="search-song-icon">search</i>
                    <label for="new-song-search">Song search</label>
                    <input id="new-song-search" type="text">

                    <ul class="show-autocomplete dropdown-content" id="search-preview" tabindex="0">

                    </ul>
                </div>
            </div>
            <h5>Your songs</h5>

            <div id="add-song-list"></div>

        </div>

        <div class="modal-footer" id="add-song-footer">
            <a class="modal-close waves-effect waves-green btn-flat left" style="margin-left: 28px;">Cancel</a>
            <a class="modal-close waves-effect waves-green btn-flat" id="add-song-button">Add Songs</a>
        </div>
    </div>


{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="../static/js/own/Playlist.js"></script>
    <script type="text/javascript" src="../static/js/own/Song.js"></script>
    <script type="text/javascript" src="../static/js/own/functions.js"></script>
    <script type="text/javascript" src="../static/js/own/playlist_functions.js"></script>
    <script type="text/javascript" src="../static/js/own/song_functions.js"></script>
    <script type="text/javascript" src="../static/js/own/search_playlist.js"></script>
    <script type="text/javascript" src="../static/js/own/song_search.js"></script>
    <script type="text/javascript" src="../static/js/own/main.js"></script>
{% endblock %}

src/server/main/templates/login.html
{% extends "base.html" %}

{% block css %}
    <style>
        #main-box > div {
            margin: 0;
            padding: 0;
        }
    </style>
{% endblock %}

{% block nav %}{% endblock %}

{% block main %}
    <form action="" method="post">
        <div id="login-modal" class="modal">
            <div class="modal-content">
                <h4>Login</h4>

                {{ form.csrf_token }}

                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">account_circle</i>
                        {{ form.username(size=32) }}
                        {{ form.username.label }}
                    </div>
                    <div class="input-field col s12">
                        <i class="material-icons prefix">lock</i>
                        {{ form.password(size=32) }}
                        {{ form.password.label }}
                    </div>

                    <div class="col s12">
                        <label style="float: right;">
                            {{ form.remember_me() }}
                            {{ form.remember_me.label() }}
                        </label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                {{ form.submit(class='btn-flat') }}
            </div>
        </div>
    </form>
{% endblock %}

{% block footer %}{% endblock %}


{% block javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let modal = document.getElementById("login-modal");
            let instance = M.Modal.init(modal, {"dismissible": false});
            instance.open();

            document.getElementById("remember_me").checked = "checked"
        });
    </script>

{% endblock %}

src/server/main/templates/playback.html
{% extends "base.html" %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="/static/css/own/playback.css" media="screen,projection"/>
{% endblock %}

{% block javascript_variables %}
    <script type="text/javascript">

        let searchAPI = "{{ url_for("api.search") }}?spotify-user-id={{ spotify_user_id }}&q=";
        let devicesAPI = "{{url_for("api.devices", spotify_user_id=spotify_user_id) }}";
        let playerAPI = "{{ url_for("api.player", spotify_user_id=spotify_user_id) }}";

        let pauseAPI = "{{ url_for("api.pause", spotify_user_id=spotify_user_id) }}";
        let playAPI = "{{ url_for("api.play", spotify_user_id=spotify_user_id) }}";
        let nextAPI = "{{ url_for("api.next", spotify_user_id=spotify_user_id) }}";
        let previousAPI = "{{ url_for("api.previous", spotify_user_id=spotify_user_id) }}";
        let addSongQueueAPI = "{{ url_for("api.add_song_to_queue", spotify_user_id=spotify_user_id) }}?track-id=";

        let spotifyUserID = "{{ spotify_user_id }}";
    </script>
{% endblock %}

{% block nav %}
{% endblock %}

{% block no_box %}
    {# Background image#}
    <div class="background-blur-image"></div>
    <img id="preloader" style="display: none">

    {# Top Row #}
    <div class="row flex no-margin"
         style="background: linear-gradient(0deg, rgba(255,255,255,0) 0%, rgba(0,0,0,0.7) 100%); height: 73px">
        {# Left side #}
        <div class="col s9 no-margin flex-v-center min-height-hundred space-between">

            {# Back button #}
            <a class="pointer flex-v-center white-text back" href="/">
                <i class="material-icons">navigate_before</i>
                <span>Home</span>
            </a>

            {#  search #}
            <i class="material-icons pointer tooltipped" id="add-to-queue" data-position="left"
               data-tooltip="Add songs to the queue">playlist_add</i>
        </div>
        {# Right side #}
        <div class="col s3 no-margin no-padding">
            <div class="flex-v-center queue-heading">
                <i class="material-icons small">playlist_play</i>
                <span class="queue-heading-text">Play Queue</span>
            </div>
        </div>
    </div>

    {# Middle row #}
    <div class="row flex no-margin" style="height: calc(100vh - 73px - 113px)">

        {# Cover and search #}
        <div class="col s9 no-margin no-padding min-height-hundred flex-v-center flex-center"
             style="position: relative;">

            {# Cover #}
            <div>
                <div class="middle">
                    <div class="preloader-wrapper big active">
                        <div class="spinner-layer spinner-blue-only">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div>
                            <div class="gap-patch">
                                <div class="circle"></div>
                            </div>
                            <div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <img class="cover-image"
                     src="/static/icons/default_playlist_cover.png"
                     alt>
                <div class="small-padding-top small-padding-bottom center cover-text small-padding-left small-padding-right">
                    <span style="width: 100%" class=" inline-block">
                        <a class="underline no-wrap to-long inline-block" href="#" target="_blank"
                           id="artist" style="max-width: 100%;">No Song</a>
                    </span>
                    <span style="width: 100%" class=" inline-block">
                        <a class="underline no-wrap to-long inline-block small-padding-left small-padding-right"
                           target="_blank" href="#" style="max-width: 100%;" id="song">Playing</a>
                    </span>
                </div>

            </div>

            {# Search field #}
            <div class="search-div small-padding" style="overflow: hidden">

                <div style="height: 100px">
                    <h5 class="no-margin-bottom no-wrap to-long no-margin-top">Search for the songs</h5>

                    <div class="input-field small-padding-bottom no-margin-bottom">
                        <input placeholder="artist:** track:** album: ** year:**" id="song-name" type="text">
                    </div>
                </div>

                <div class="search-preview">
                    {# The song search #}
                </div>
            </div>

        </div>

        {# Right side (queue) #}
        <div class="col s3 min-height-hundred no-margin no-padding-left no-padding-right" id="queue">


        </div>

    </div>

    {# Bottom row #}
    <div class="row playback-group no-margin flex" style="height: 113px">
        {# Left side#}
        <div class="col s9 no-margin">
            {# Progress bar #}
            <div class="row flex-center">
                <span class="col" id="current-time">00:00</span>
                <div class="col s8 m9 l10 xl10">
                    <div class="progress">
                        <div class="determinate"></div>
                    </div>
                </div>
                <span class="col no-padding-right" id="total-time">00:00</span>
            </div>

            {# Left controls #}
            <div class="row flex-v-center">
                <div class="playback-controls">

                    <i class="material-icons pointer playback-control" id="shuffle">shuffle</i>

                    <i class="material-icons pointer playback-control" id="previous">skip_previous</i>

                    <a class="pointer btn-floating playback-control" id="play" style="display: none">
                        <i class="material-icons">play_arrow</i>
                    </a>
                    <a class="pointer btn-floating playback-control" id="pause"><i class="material-icons">pause</i></a>

                    <i class="material-icons pointer playback-control" id="next">skip_next</i>

                    <i class="material-icons pointer playback-control" id="repeat">repeat</i>
                    <i class="material-icons pointer playback-control" id="repeat-one"
                       style="display: none">repeat_one</i>

                </div>

                {# Right controls #}
                <div class="right-controls">

                    {# Device button #}
                    <i class="material-icons pointer" id="devices-button">devices_other</i>

                    {# Device menue #}
                    <div class="device-text">
                        <span style="background-color: var(--darker); display: inline-block">
                            <h6 class="no-wrap device-padding">Connect to a device</h6>
                            <div style="text-align: center; padding-left: 50px; padding-right: 50px">
                                <img src="/static/icons/devices.png" class="small-padding-top small-padding-bottom"
                                     style="width: 180px;" alt="">
                            </div>

                            <div id="devices">
                                <div class="device-padding small-margin-bottom">
                                    <p class="no-margin">Play and control the Spotify playback on all your devices.</p>
                                    <p class="no-margin">Start Spotify on another device, start playing.</p>
                                    <a class="btn btn-flat" href="https://www.spotify.com/de/connect/">Lean more</a>
                                </div>
                            </div>
                        </span>
                    </div>

                </div>
            </div>
        </div>
        {# Right queue info #}
        <div class="col s3 flex-v-center flex-center no-margin" style="min-height: 100%; background: var(--darker)">
            <a id="scroll-current" class="btn-floating btn-large tooltipped" data-position="left"
               data-tooltip="Scroll to current track"><i class="material-icons">playlist_play</i></a>

            <p class="no-margin flex-break" style="font-size: 1.5rem; text-align: center;">Remaining time</p>
            <p class="no-margin" id="queue-duration">00:00:00</p>
        </div>
    </div>
{% endblock %}

{% block main %}{% endblock %}
{% block footer %}{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="/static/js/libraries/color-thief.js"></script>
    <script type="text/javascript" src="/static/js/libraries/socket.io.js"></script>
    <script type="text/javascript" src="/static/js/own/playback/main.js"></script>
    <script type="text/javascript" src="/static/js/own/playback/search.js"></script>
    <script type="text/javascript" src="/static/js/own/playback/devices.js"></script>
    <script type="text/javascript" src="/static/js/own/playback/playback.js"></script>
    <script type="text/javascript" src="/static/js/own/playback/queue.js"></script>
    <script type="text/javascript" src="/static/js/own/playlist/Song.js"></script>
{% endblock %}

src/server/main/templates/select.html
{% extends "base.html" %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="/static/css/own/select.css" media="screen,projection"/>

    <style>
        .z-depth-3 {
            box-shadow: none;
        }
    </style>
{% endblock %}

{% block main %}

    <div class="center">
        <h3 style="text-align: left; padding-left: .75rem">Select a Playlist</h3>

        {# If the user has not playlists #}
        {% if playlist_list_json == {} %}
            <ul>
                <li class="divider"></li>
            </ul>
            <h6 class="margin-top">Your user currently has no playlist assigned to him</h6>
        {% endif %}

        <div class="row flex-center">


            {# For every playlist of the user #}
            {% for id, playlist in playlist_list_json.items() %}

                <div class="col xs12 s5 m4 l3 xl2 small-margin-bottom">
                    <div class="card">
                        <a href="{{ url_for("main.playlist", playlist_id=playlist["id"]) }}">
                            <div class="card-image pointer" hover-on-touch>
                                <img alt="cover image" src="{{ playlist["image_url"] }}">
                            </div>
                        </a>

                        <div class="card-content">
                            <a class="card-title black-text underline pointer to-long no-wrap"
                               href="{{ url_for("main.playlist", playlist_id=playlist["id"]) }}">
                                {{ playlist["name"] }}
                            </a>
                            <a class="pointer black-text underline to-long no-wrap" style="display: block"
                               href="{{ playlist["author"]["url"] }}">
                                {{ playlist["author"]["name"] }}
                            </a>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
    </div>
{% endblock %}