src/server/admin/routes.py
from argon2 import PasswordHasher, Type
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

from server import db
from server.admin.admin_functions import display_all_spotify_users, display_spotify_user_playlists, display_user, \
    display_all_users, password_complex_enough
from server.admin.forms import ChangePasswordForm
from server.main.modals import User

mod = Blueprint("admin", __name__, template_folder='templates')


@mod.route("/spotify-users")
@login_required
def spotify_users() -> render_template:
    """
    Display one or all spotify users depending on the args in the url
    :return:
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the spotify id of a use in a url
    spotify_user_id = request.args.get("spotify-user-id")

    # Check if a use id is present in the url
    if spotify_user_id:
        return display_spotify_user_playlists(spotify_user_id)
    else:
        return display_all_spotify_users()


@mod.route("/users")
@login_required
def users() -> render_template:
    """
    Display the users or one user
    :return: A rendered template
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the user-id from the url
    user_id = request.args.get("user-id")

    # Check if a user id is given in the url
    if user_id:
        return display_user(user_id)

    return display_all_users()


@mod.route("/user/change_password", methods=["POST", "GET"])
def edit_user() -> redirect:
    """
    Edit the user password
    :return: a redirect to the user page
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    # Get the user-id from the url
    user_id = request.args.get("user-id")

    # Check if a user id is given in the url
    if not user_id:
        flash({"contend": "No user id was provided", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    if current_user.id != int(user_id) and not current_user.is_root:
        return render_template("authorisation_error.html", title="403")

    form = ChangePasswordForm()

    if form.confirmed_new_password.data == (None or "") and form.new_password.data == (None or "") \
            and form.current_password.data == (None or ""):
        flash({"contend": "You did not input all the required forms", "type": "bg-warning"})
        return redirect(url_for("admin.users") + f"?user-if={user_id}")

    # checks if all relevant data filed have been filled
    if current_user.check_password(form.current_password.data) or \
            (current_user.is_root and not current_user.id == int(user_id)):

        if form.new_password.data == form.confirmed_new_password.data:

            if not password_complex_enough(form.new_password.data):
                flash({"contend": "The password is not complex enough. (Upper + Lower + Digits)", "type": "bg-warning"})

            user = User.query.filter(User.id == int(user_id)).first()
            user.set_password(form.confirmed_new_password.data)
            db.session.commit()
            return redirect(url_for("admin.users") + f"?user-id={user.id}")
        else:
            flash({"contend": "The passwords did not match", "type": "bg-warning"})
            return redirect(url_for("admin.users") + f"?user-id={user_id}")

    else:
        flash({"contend": "You provided the wrong password", "type": "bg-warning"})
        return redirect(url_for("admin.users") + f"?user-id={user_id}")


@mod.route("/user/add", methods=["POST", "GET"])
@login_required
def add_user() -> redirect:
    """
    Add a new user
    :return: a redirect to the user page
    """

    if not current_user.is_admin:
        return render_template("authorisation_error.html", title="403")

    password = request.form["password"]
    username = request.form["username"]

    # Check if the user should be a admin
    if "is_admin" in request.form:
        admin = True
    else:
        admin = False

    if password is None or username is None or username == "":
        flash({"contend": "You did not fill a username or password", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    # Check if the username already exists and do nothing if the user exists
    if User.query.filter(User.username == username).first():
        flash({"contend": "The user already exists", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    # Create a password hasher
    ph = PasswordHasher(type=Type.ID)

    if not password_complex_enough(password):
        flash({"contend": "The password is not complex enough. (Upper + Lower + Digits)", "type": "bg-warning"})
        return redirect(url_for("admin.users"))

    password_hash = ph.hash(password)

    # Create the neu user and add it into the database
    user = User(username=username, password_hash=password_hash, is_admin=admin)
    db.session.add(user)
    db.session.commit()

    return redirect(url_for("admin.users"))

src/server/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user, logout_user, login_user

from server import spotify
from server.api.api_functions import get_token_by_playlist, modify_playlist_json
from server.main.forms import LoginForm
from server.main.modals import User, Playlist, SpotifyUser

mod = Blueprint("main", __name__, template_folder='templates')


@mod.route("/")
@login_required
def home() -> render_template:
    """
    The default rote that lets you select a playlist
    :return: A template
    """

    user = current_user.id
    playlist_list = Playlist.query.join(User.playlists).filter(User.id == user).all()

    playlist_list_json = {}
    for playlist in playlist_list:
        auth_token = get_token_by_playlist(playlist.spotify_id)

        if auth_token:
            playlist_list_json[playlist.spotify_id] = \
                modify_playlist_json(spotify.playlist(playlist.spotify_id, auth_token))

    return render_template("select.html", title="Select Playlist", playlist_list_json=playlist_list_json)


@mod.route("/playlist/<playlist_id>")
@login_required
def playlist(playlist_id) -> render_template:
    # Get a playlist from the database
    spotify_playlist: Playlist = Playlist.query.filter(Playlist.spotify_id == playlist_id).first()

    # If the playlist is not in the db render the resource not found
    if not spotify_playlist:
        return render_template("resource_not_found.html", title="Resource not found", resource="Playlist")

    # Render the playlist page
    return render_template("playlist.html", title="Home", playlist_id=playlist_id, spotify_playlist=spotify_playlist)


@mod.route("/playback/<spotify_user_id>")
@login_required
def playback(spotify_user_id):
    spotify_user = SpotifyUser.query.filter(SpotifyUser.spotify_user_id == spotify_user_id).first()
    if not spotify_user:
        return render_template("resource_not_found.html", title="Resource not found", resource="Spotify User")

    # ToDo make secure
    # return render_template("angular/index.html", title="Playback", spotify_user_id="spotify_user_id")
    return render_template("playback.html", title="Playback", spotify_user_id=spotify_user_id)


@mod.route("/login", methods=["GET", "POST"])
def login() -> redirect:
    """
    Login page
    :return: A redirect
    """

    # Redirect the user to home if he is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()

    # checks if all relevant data filed have been filled
    if form.validate_on_submit():
        # get the user that logged in
        user = User.query.filter_by(username=form.username.data).first()

        # if the user does not exist or has the wrong password
        if user is None or not user.check_password(form.password.data):
            flash({"contend": "Invalid username or password", "type": "bg-warning"})
            return redirect(url_for("main.login"))

        # login the user
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if next_page:
            if not str(next_page[0]) == "/":
                next_page = "/" + next_page

            return redirect(f"{next_page}")
        else:
            return redirect(url_for("main.home"))

    # Handle invalid form
    if request.method == "POST":
        flash({"contend": "You missed some input fields", "type": "bg-warning"})
        return render_template('login.html', title='Sign In', form=form)

    return render_template('login.html', title='Sign In', form=form)


@mod.route("/logout")
@login_required
def logout():
    """
    Logout the user
    :return:
    """
    logout_user()
    return redirect(url_for('main.login'))

src/server/templates/authorisation_error.html
{% extends "base.html" %}
{% block main %}

    <div class="section" id="index-banner">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <h1 class="red-text text-lighten-1 center">403</h1>
                    <h4 class="light red-text text-lighten-3 center">You are not authorized to visit this page</h4>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}

{% endblock %}

src/server/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <link rel="icon" href="/static/icons/Spotify.png">

    <!--Import Google Icon Font-->
    <link href="/static/css/libraries/materiel-icons.css" rel="stylesheet">

    <!--Import CSS-->
    <link type="text/css" rel="stylesheet" href="/static/css/libraries/materialize.min.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/main.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/hover.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/color.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/helpers.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/responsive.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/label_checkbox.css"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/own/responsive_table.css"
          media="screen,projection"/>


    {% if current_user.is_admin %}
        <link type="text/css" rel="stylesheet" href="/static/css/libraries/tablesort.css"
              media="screen,projection"/>
    {% endif %}


    {% block css %}{% endblock %}

    {% block javascript_variables %}{% endblock %}

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="Description" content="A website made to collaborate on multible spotify playlists">
    <meta charset="UTF-8">


    <link rel="manifest" href="/static/pwa/manifest.json">


    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    <meta name="apple-mobile-web-app-title" content="With Manifest">

    <link rel="apple-touch-icon" href="/static/pwa/images/icons/icon-152x152.png" sizes="152x152">

</head>
<body>

{% block nav %}

    {% if current_user.is_admin %}
        <nav>
            <div class="nav-wrapper">
                <ul class="left hide-on-med-and-down">
                    <li><a href="{{ url_for("admin.spotify_users") }}">Spotify Users</a></li>
                    <li><a href="{{ url_for("admin.users") }}">Users</a></li>
                </ul>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <a href="/" class="brand-logo center">HOME</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{{ url_for("main.logout") }}">Logout</a></li>
                </ul>
            </div>
        </nav>

        <ul class="sidenav" id="mobile-demo">

            <li class="nav-logo"></li>

            <li class="divider"></li>

            <li><a href="{{ url_for("admin.spotify_users") }}" tabindex="-1">Spotify Users</a></li>
            <li><a href="{{ url_for("admin.users") }}" tabindex="-1">Users</a></li>
            <li><a href="{{ url_for("main.logout") }}" tabindex="-1">Logout</a></li>
        </ul>

    {% else %}
        <nav>
            <div class="nav-wrapper">
                <a href="/" class="brand-logo left small-padding-left">HOME</a>
                <ul class="right">
                    <li><a href="{{ url_for("main.logout") }}">Logout</a></li>
                </ul>
            </div>
        </nav>
    {% endif %}
{% endblock %}

{% block no_box %}{% endblock %}

<div id="main-box">
    <div class="container margin-top z-depth-3 rounded small-padding">
        {% block main %}        {% endblock %}
    </div>
</div>



{% block footer %}
    <footer class="margin-top page-footer" style="z-index: 1000; position: relative">
        <div class="container">
            <div class="row">
                <div class="col l6 m6 s12">
                    <h5 class="white-text">Playlist Editor</h5>
                    <p class="grey-text text-lighten-4">
                        A Webapp that allows you to edit a playlist as a group.
                    </p>
                </div>
                <div class="col l4 offset-l2 m4 offset-m2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul class="footer-links">
                        <li class="valign-wrapper">
                            <img class="footer-image" alt="" src="../static/icons/GitHub-120px-dark.png">
                            <a class="grey-text text-lighten-3" hover-on-touch
                               href="https://github.com/HuiiBuh/spotify-playlist-colloboration">
                                Fork on Github
                            </a>
                        </li>
                        <li class="valign-wrapper">
                            <img class="footer-image" alt="" src="../static/icons/GitHub-120px-dark.png">
                            <a class="grey-text text-lighten-3" hover-on-touch
                               href="https://github.com/HuiiBuh/">HuiiBuh</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col s9" id="copyright">
                        © 2019 HuiBuh
                    </div>
                </div>
            </div>
        </div>
    </footer>

{% endblock %}

<script type="text/javascript" src="/static/js/libraries/materialize.min.js"></script>
<script type="text/javascript" src="/static/js/own/useful_functions.js"></script>
<script type="text/javascript" src="/static/js/own/hoverontouch.js"></script>
<script type="text/javascript" src="/static/js/own/init.js"></script>

{% if current_user.is_admin %}
    <script type="text/javascript" src="/static/js/libraries/tablesort.min.js"></script>
    <script type="text/javascript" src="/static/js/libraries/tablesort.number.min.js "></script>
    <script type="text/javascript">
        let sort;
        try {
            sort = new Tablesort(document.getElementsByTagName("table")[0]);
        } catch (Error) {

        }
    </script>
{% endif %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <script type="text/javascript">
                M.toast({html: "{{ message.contend }}", classes: "{{message.type}}"});
            </script>
        {% endfor %}
    {% endif %}
{% endwith %}



{% block javascript %}{% endblock %}

</body>
</html>

src/server/templates/index.html
{% extends "base.html" %}

{% block main %}

    <div id="main-box">
        <div class="container margin-top z-depth-3 rounded" id="playlist-box">

            <div class="center small-padding-top">
                <h1 id="playlist-title">Muay Thai</h1>
            </div>

            <!-- Playlist information -->
            <div class="row flex-v-center">
                <div class="col s9">
                    <table>
                        <tbody>
                        <tr>
                            <td>Author</td>
                            <td>HuiiBuh</td>
                        </tr>
                        <tr>
                            <td>Duration</td>
                            <td>22h</td>
                        </tr>
                        <tr>
                            <td>Song Count</td>
                            <td>500</td>
                        </tr>
                        <tr style="border-bottom:none!important;">
                            <td>URL</td>
                            <td><a href="https://spotify.com">Go to Spotify</a></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col s3 center">
                    <img alt="Cover image" class="cover-image cover-image col s12 no-padding"
                         src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg">
                </div>
            </div>
            <ul>
                <li class="divider"></li>
            </ul>
            <!-- Song heading -->
            <div class="row">
                <h4 class="col s12 no-margin-bottom">Songs</h4>
            </div>

            <!-- All songs -->
            <div id="playlist-songs">
                <div class="row flex-v-center song rounded">
                    <div class="col xs3 s2 l1 flex-v-center">
                        <img alt="cover" class="song-image no-padding"
                             src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg"
                             onclick="window.open('https://open.spotify.com/track/6ZFbXIJkuI1dVNWvzJzown')">
                    </div>
                    <div class="col xs8 s9 l10">
                        <div class="col s12">Title</div>
                        <div class="col s12">Interpret &middot; Album</div>
                    </div>
                    <div class="col xs1 s1">
                        <p>5:50 min</p>
                    </div>
                </div>

                <div class="row flex-v-center song rounded">
                    <div class="col xs3 s2 l1 flex-v-center">
                        <img alt="cover" class="song-image no-padding"
                             src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg"
                             onclick="window.open('https://open.spotify.com/track/6ZFbXIJkuI1dVNWvzJzown')">
                    </div>
                    <div class="col xs8 s9 l10">
                        <div class="col s12">Title</div>
                        <div class="col s12">Interpret &middot; Album</div>
                    </div>
                    <div class="col xs1 s1">
                        <p>5:50 min</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Action button -->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large modal-trigger" href="#song-modal">
            <i class="very-large material-icons pointer">add</i>
        </a>
    </div>




    <div id="song-modal" class="modal">
        <div class="modal-content">
            <h4>Search for Songs</h4>

            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix" id="search-song-icon">search</i>
                    <input id="song-search" type="text" class="validate">
                    <label for="song-search">Song search</label>

                    <ul class="show-autocomplete dropdown-content" tabindex="0">

                        <li class="search-song">
                            <div class="flex-v-center small-padding-bottom small-padding-top">
                                <div class="col xs3 s2 l1 flex-v-center">
                                    <img alt="cover" class="search-song-image no-padding"
                                         src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg">
                                </div>
                                <div class="col xs8 s9 m9 l10">
                                    <div class="col s12">Title</div>
                                    <div class="col s12">Interpret &middot; Album</div>
                                </div>
                                <div class="col xs1 s2 m2 l1 flex-end  flex-v-center">
                                    <i class="material-icons pointer">playlist_add</i>
                                </div>
                            </div>
                        </li>

                        <li class="search-song">
                            <div class="flex-v-center small-padding-bottom small-padding-top">
                                <div class="col xs3 s2 l1 flex-v-center">
                                    <img alt="cover" class="search-song-image no-padding"
                                         src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg">
                                </div>
                                <div class="col xs8 s9 m9 l10">
                                    <div class="col s12">Title</div>
                                    <div class="col s12">Interpret &middot; Album</div>
                                </div>
                                <div class="col xs1 s2 m2 l1 flex-end  flex-v-center">
                                    <i class="material-icons pointer">playlist_add</i>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
            <h5>Your songs</h5>

            <div id="add-song-list">
                <div class="row flex-v-center song rounded add-song-list "
                     onclick="window.open('https://open.spotify.com/track/6ZFbXIJkuI1dVNWvzJzown')">
                    <div class="col xs3 s2 l1 flex-v-center">
                        <img alt="cover" class="song-image no-padding"
                             src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg">
                    </div>
                    <div class="col xs8 s9 l9">
                        <div class="col s12">Title</div>
                        <div class="col s12">Interpret &middot; Album</div>
                    </div>
                    <div class="col xs1 s2 flex-v-center flex-end">
                        <i class="material-icons pointer">delete</i>
                    </div>
                </div>


                <div class="row flex-v-center song rounded add-song-list "
                     onclick="window.open('https://open.spotify.com/track/6ZFbXIJkuI1dVNWvzJzown')">
                    <div class="col xs3 s2 l1 flex-v-center">
                        <img alt="cover" class="song-image no-padding"
                             src="https://cdn.shopify.com/s/files/1/1040/6126/products/eminem-revival-uni-universal-music.jpg">
                    </div>
                    <div class="col xs8 s9 l9">
                        <div class="col s12">Title</div>
                        <div class="col s12">Interpret &middot; Album</div>
                    </div>
                    <div class="col xs1 s2 flex-v-center flex-end">
                        <i class="material-icons pointer">delete</i>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer" id="add-song-footer">
            <a class="modal-close waves-effect waves-green btn-flat">Add Songs</a>
        </div>
    </div>


{% endblock %}

{% block javascript %}
    <script src="../static/js/own/main.js"></script>
{% endblock %}

src/server/templates/resource_not_found.html
{% extends "base.html" %}

{% block main %}

    <div class="section" id="index-banner">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <h1 class="red-text text-lighten-1 center">404</h1>
                    <h4 class="light red-text text-lighten-3 center">The {{ resource }} you asked for does not
                        exist.</h4>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}

{% endblock %}